development:
  adapter: postgresql
  encoding: unicode
  database: kite_development
  pool: 5
  username: brianholt
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: kite_test
  pool: 5
  username: brianholt
  password:
